{{- if .Values.services.ingress -}}
---
# The cert and the key cannot be filled automatically. If we could it
# would roughly look like the lines below. As is it is the
# responsibility of the operator to retrieve the values of these
# secrets from the deployed SCF and update this secret with the actual
# values. And the responsibility of the developer to supply the proper
# instructions to the operator.
##
# tls.crt: {{ default "" .Values.secrets.ROUTER_SSL_CERT     | b64enc | quote }}
# tls.key: {{ default "" .Values.secrets.ROUTER_SSL_CERT_KEY | b64enc | quote }}

apiVersion: "v1"
kind: "Secret"
type: kubernetes.io/tls
metadata:
  name: "{{ .Values.services.ingress.class }}-ingress-tls"
  namespace: "{{ .Release.Namespace }}"
data:
  tls.crt: ""
  tls.key: ""
---
# This ingress specifies routing and access for the cloud controller
# public SCF service, i.e. "api.<domain>" and other services in that
# domain hierarchy.
#
# Note that the two other services (tcp routing, app ssh access) are
# not suitable to routing via http, and not specified. IOW they are
# TCP, which is not supported by the current ingress specification.
# Although specific controllers may do so in a custom manner.

apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "{{ .Release.Name }}-{{ .Values.services.ingress.class }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.services.ingress.class }}
    {{ if eq .Values.services.ingress.class "nginx" -}}
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Doesn't enforce HTTPS.
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    {{- end }}
spec:
  tls:
  - secretName: "{{ .Values.services.ingress.class }}-ingress-tls"
    hosts:
    - "*.{{ .Values.env.DOMAIN }}"
    - "{{ .Values.env.DOMAIN }}"
  rules:
    - host: "*.{{ .Values.env.DOMAIN }}"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "router-gorouter-public"
              servicePort: {{ .Values.services.ingress.backends.router.port }}
    - host: "{{ .Values.env.DOMAIN }}"
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "router-gorouter-public"
              servicePort: {{ .Values.services.ingress.backends.router.port }}
{{- end }}
