# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=doppler/jobs/name=log-cache-expvar-forwarder
- type: remove
  path: /instance_groups/name=doppler/jobs/name=log-cache-cf-auth-proxy

# Override the addresses for the jobs under the doppler instance group.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar/properties/nats?/machines
  value:
  - ((deployment-name))-nats
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar/properties/route_registrar?/routing_api/api_url
  value: http://((deployment-name))-api:3000
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar/properties/route_registrar?/routing_api/oauth_url
  value: https://((deployment-name))-uaa:8443

# Add bosh_containerization properties for doppler.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=doppler/properties/bosh_containerization?
  value:
    run:
      memory: 410
      virtual-cpus: 2

# Add bosh_containerization properties for log-cache.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache/properties/bosh_containerization?
  value:
    ports:
    - name: log-cache
      protocol: TCP
      internal: 8080
    run:
      memory: 256
      virtual-cpus: 2
