# Override the addresses for the jobs under the doppler instance group.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar/properties/nats?/machines
  value:
  - {{ .Values.deployment_name }}-nats
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar/properties/route_registrar?/routing_api/api_url
  value: http://{{ .Values.deployment_name }}-api:3000
- type: replace
  path: /instance_groups/name=doppler/jobs/name=route_registrar/properties/route_registrar?/routing_api/oauth_url
  value: https://{{ .Values.deployment_name }}-uaa:8443

# Change the log_cache_ca CN to avoid clashing with the other log-cache certificate CNs.
- type: replace
  path: /variables/name=log_cache_ca/options/common_name
  value: log-cache-ca

# Add quarks properties for doppler.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=doppler/properties/quarks?
  value:
    ports:
    - name: dropsonde-tcp
      protocol: TCP
      internal: 3458
    - name: doppler-tls
      protocol: TCP
      internal: 3459
    - name: doppler-ws
      protocol: TCP
      internal: 8081
    - name: doppler-grpc
      protocol: TCP
      internal: 8082
    - name: log-cache-proxy # log-cache-cf-auth-proxy
      protocol: TCP
      internal: 8083

# Add quarks properties for log-cache.
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache/properties/quarks?
  value:
    ports:
    - name: log-cache
      protocol: TCP
      internal: 8080


- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-expvar-forwarder/properties/quarks?/envs?
  value:
  - name: INSTANCE_ADDR
    value: {{ .Values.deployment_name }}-doppler:8080
  - name: INSTANCE_ID
    value: "0"
