{{- if eq .Values.features.eirini true}}

# Add eirini
- type: replace
  path: /instance_groups/-
  value:
    name: eirini
    release: eirini
    instances: 1
    vm_type: minimal
    stemcell: default
    networks:
    - name: default
    env:
      bosh:
        agent:
          settings:
            serviceAccountName: ((deployment-name))-eirini
    jobs:
    - name: opi
      release: eirini
      properties:
        opi:
          server_cert: ((eirini_tls_server_cert.certificate))
          server_key: ((eirini_tls_server_cert.private_key))
          client_ca: ((service_cf_internal_ca.certificate))
          kube_namespace: ((deployment-name))-eirini
          kube_service_host: ""
          kube_service_port: ""
          registry_address: registry.((system_domain))
          nats_password: ((nats_password))
          nats_ip: ((deployment-name))-nats
          certs_secret_name: eirini-staging-secret
          cc_internal_api: https://((deployment-name))-api:9023
          cc_uploader_ip: ""
          eirini_address: https://((deployment-name))-eirini:8484
          downloader_image: "eirini/recipe-downloader"
          uploader_image: "eirini/recipe-uploader"
          executor_image: "eirini/recipe-executor"
          metrics_source_address: ""
          loggregator_address: localhost:3458
          loggregator_cert: ((loggregator_tls_agent.certificate))
          loggregator_key: ((loggregator_tls_agent.private_key))
          loggregator_ca: ((loggregator_tls_agent.certificate))
          cc_cert: ((cc_bridge_tps.certificate))
          cc_key: ((cc_bridge_tps.private_key))
          cc_ca: ((service_cf_internal_ca.certificate))
- type: replace
  path: /variables/name=eirini_tls_server_cert?
  value:
    name: eirini_tls_server_cert
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: ((deployment-name))-eirini
      extended_key_usage:
      - server_auth
- type: replace
  path: /variables/name=eirini_tls_client_cert?
  value:
    name: eirini_tls_client_cert
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: cloud_controller
      extended_key_usage:
      - client_auth

# Attach a persistent disk to bits-service VM to store eirinifs
# TODO: storage class type should be configurable
# - type: replace
#   path: /instance_groups/name=bits/persistent_disk_type?
#   value: ???
- type: replace
  path: /instance_groups/name=bits/persistent_disk?
  value: 20480 # 20GB

# Enable Docker registry on bits-service (used by OPI)
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/enable_registry?
  value: true
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/registry_endpoint?
  value: "https://registry.((system_domain))"
- type: replace
  path: /instance_groups/name=bits/jobs/name=route_registrar/properties/route_registrar/routes/name=bits-service/uris/-
  value: registry.((system_domain))
- type: replace
  path: /variables/name=bits_service_ssl/options/alternative_names/-
  value: registry.((system_domain))

# Add eirinifs job to the bits-service to copy the tarball into the bits-service VM
- type: replace
  path: /instance_groups/name=bits/jobs/name=eirinifs?
  value:
    name: eirinifs
    release: eirini
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/rootfs?/blobstore_type?
  value: local

- type: replace
  path: /releases/-
  value: 
    name: eirini
    version: 0.0.15
    url: ((releases-defaults-url))
    stemcell:
      alias: default
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_346.ge9dd9ff3

# Enable OPI in CC
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/enabled?
  value: true
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/url?
  value: https://((deployment-name))-eirini:8484
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/opi_staging?
  value: true
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/client_cert?
  value: ((eirini_tls_client_cert.certificate))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/client_key?
  value: ((eirini_tls_client_cert.private_key))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/ca_cert?
  value: ((eirini_tls_server_cert.ca))

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/enabled?
  value: true
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/url?
  value: https://((deployment-name))-eirini:8484
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/opi_staging?
  value: true
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/client_cert?
  value: ((eirini_tls_client_cert.certificate))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/client_key?
  value: ((eirini_tls_client_cert.private_key))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/ca_cert?
  value: ((eirini_tls_server_cert.ca))

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/enabled?
  value: true
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/url?
  value: https://((deployment-name))-eirini:8484
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/opi_staging?
  value: true
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/client_cert?
  value: ((eirini_tls_client_cert.certificate))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/client_key?
  value: ((eirini_tls_client_cert.private_key))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/ca_cert?
  value: ((eirini_tls_server_cert.ca))

# Add quarks information to the Eirini jobs
- type: replace
  path: /instance_groups/name=eirini/jobs/name=opi/properties/quarks?
  value:
    ports:
    - name: opi
      protocol: TCP
      internal: 8484

- type: replace
  path: /instance_groups/name=bits/jobs/name=eirinifs/properties?/quarks?
  value:
    bpm:
      processes: []
{{- end}}
