# ops for the log-api instance group
# Initial: remove all the jobs

- type: remove
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy
- type: remove
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy_gateway
- type: remove
  path: /instance_groups/name=log-api/jobs/name=route_registrar

# Attention: scf/fissile does not use the reverse_log_proxy_gateway
# We may be able to go without this job

# Set loggegrator stemcell to get around issues with the CI not building the general one.
# See buildpacks in api.yaml as well.
# (ak) TODO: Remove when we have a proper CI pipeline for stemcells and images.
- type: replace
  path: /releases/name=loggregator/stemcell?
  value:
    os: opensuse-42.3
    version: 36.g03b4653-30.80-7.0.0_340.g2b599a90

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/bosh_containerization?
  value:
    run:
      memory: 128
      virtual-cpus: 2
    ports:
    - name: dropsonde
      protocol: TCP
      internal: 8081
