# ops for the log-api instance group
# Initial: remove all the jobs

- type: remove
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy
- type: remove
  path: /instance_groups/name=log-api/jobs/name=reverse_log_proxy_gateway
- type: remove
  path: /instance_groups/name=log-api/jobs/name=route_registrar

# Attention: scf/fissile does not use the reverse_log_proxy_gateway
# We may be able to go without this job

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/bosh_containerization?
  value:
    run:
      memory: 128
      virtual-cpus: 2
    ports:
    - name: dropsonde
      protocol: TCP
      internal: 8081
