# Add bosh_containerization properties.
- type: replace
  path: /instance_groups/name=nats/jobs/name=nats/properties/bosh_containerization?
  value:
    ports:
    - name: nats
      protocol: TCP
      internal: 4222
    - name: nats-routes
      protocol: TCP
      internal: 4223
