# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=router/jobs/name=loggr-udp-forwarder

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/dns_health_check_host?
  value: ((deployment-name))-uaa

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/uaa/token_endpoint?
  value: ((deployment-name))-uaa

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api/uri?
  value: https://((deployment-name))-api-group

# Set release version
- type: replace
  path: /releases/name=routing/version
  value: "0.188.0"
