# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar

# Set the common name for the blobstore_tls.
- type: replace
  path: /variables/name=blobstore_tls/options/common_name?
  value: scf-singleton-blobstore

# Configure the persistent disk in the way that cf-operator can provision.
- type: remove
  path: /instance_groups/name=singleton-blobstore/persistent_disk_type
- type: replace
  path: /instance_groups/name=singleton-blobstore/persistent_disk?
  value: 102400 # 100GB

- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=blobstore/properties/bosh_containerization?
  value:
    pre_render_scripts:
    # The setup_blobstore_directories function in the BOSH pre-start should run on all instances.
    - |
      set -o errexit

      patch --unified /var/vcap/all-releases/jobs-src/capi/blobstore/templates/pre-start.sh.erb << EOT
      @@ -20,14 +20,10 @@

         chown vcap:vcap \$store_dir
         local dirs="\$run_dir \$log_dir \$store_tmp_dir \$data_dir \$data_tmp_dir \$nginx_webdav_dir \${nginx_webdav_dir}/.."
      -  local num_needing_chown=\$(find \$dirs -not -user vcap -or -not -group vcap | wc -l)
      -
      -  if [ \$num_needing_chown -gt 0 ]; then
      -    echo "chowning \${num_needing_chown} files to vcap:vcap"
      -    find \$dirs -not -user vcap -or -not -group vcap | xargs chown vcap:vcap
      -  else
      -    echo "no chowning needed, all relevant files are vcap:vcap already"
      -  fi
      +  for dir in \${dirs}; do
      +    echo "Setting ownership of \${dir} to vcap:vcap recursively"
      +    chown --recursive vcap:vcap "\${dir}"
      +  done
       }

       <% if spec.bootstrap %>
      EOT
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 4443
    run:
      memory: 512
      virtual-cpus: 2
      healthcheck:
        nginx: &healthcheck
          readiness: &probe
            exec:
              command: ['sh', '-c', 'ss -nlt | grep "LISTEN.*:8080" && ss -nlt | grep "LISTEN.*:4443"']
          liveness: *probe
        url_signer: *healthcheck
