# Override the database address.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/address?
  value: ((deployment-name))-database

# Add the ((deployment-name))-uaa alternative name for the uaa_ssl.
- type: replace
  path: /variables/name=uaa_ssl/options/alternative_names/-
  value: ((deployment-name))-uaa

# Override the addresses for the jobs under the uaa instance group.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/zones/internal/hostnames
  value:
  - ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/nats?/machines
  value:
  - ((deployment-name))-nats
- type: replace
  path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/route_registrar?/routing_api/api_url
  value: http://((deployment-name))-api:3000
- type: replace
  path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/route_registrar?/routing_api/oauth_url
  value: https://((deployment-name))-uaa:8443

# Add bosh_containerization properties.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/bosh_containerization?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 8443
    run:
      memory: 1532
      virtual-cpus: 2
      healthcheck:
        uaa:
          readiness:
            exec:
              command: ['sh', '-c', '/var/vcap/jobs/uaa/bin/health_check']
