# Override the database address.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/address?
  value: scf-database

# Add the scf-uaa alternative name for the uaa_ssl.
- type: replace
  path: /variables/name=uaa_ssl/options/alternative_names/-
  value: scf-uaa

# Add bosh_containerization properties.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/bosh_containerization?
  value:
    ports:
    - name: uaa
      protocol: TCP
      internal: 8080
    run:
      memory: 1532
      virtual-cpus: 2
      healthcheck:
        uaa:
          readiness: &probe
            handler:
              exec:
                command: ['sh', '-c', '/var/vcap/jobs/uaa/bin/health_check']
          liveness: *probe

# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=uaa/jobs/name=route_registrar
- type: remove
  path: /instance_groups/name=uaa/jobs/name=statsd_injector
