# This is a temporary file used for selectively removing variables during the initial development.
# It should go away once all instance_groups work properly with cf-operator.

- type: remove
  path: /variables/name=silk_ca
- type: remove
  path: /variables/name=silk_controller
- type: remove
  path: /variables/name=silk_daemon
- type: remove
  path: /variables/name=network_policy_ca
- type: remove
  path: /variables/name=network_policy_server
- type: remove
  path: /variables/name=network_policy_client
- type: remove
  path: /variables/name=cf_bosh_password
- type: remove
  path: /variables/name=diego_bbs_encryption_keys_passphrase
- type: remove
  path: /variables/name=credhub_encryption_password
- type: remove
  path: /variables/name=diego_auctioneer_client
- type: remove
  path: /variables/name=diego_auctioneer_server
- type: remove
  path: /variables/name=diego_bbs_client
- type: remove
  path: /variables/name=diego_bbs_server
- type: remove
  path: /variables/name=diego_rep_client
- type: remove
  path: /variables/name=diego_rep_agent_v2
- type: remove
  path: /variables/name=adapter_rlp_tls
- type: remove
  path: /variables/name=scheduler_api_tls
- type: remove
  path: /variables/name=adapter_tls
- type: remove
  path: /variables/name=scheduler_client_tls
  path: /variables/name=cc_bridge_tps
- type: remove
  path: /variables/name=cc_bridge_cc_uploader
- type: remove
  path: /variables/name=cc_bridge_cc_uploader_server
- type: remove
  path: /variables/name=diego_instance_identity_ca
- type: remove
  path: /variables/name=credhub_tls
- type: remove
  path: /variables/name=ssh_proxy_backends_tls
