---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.deployment_name }}-eirini
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment_name }}-eirini
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.deployment_name }}-eirini
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deployment_name }}-eirini
    namespace: {{ .Release.Namespace | quote }}
