name: v3 publish

on:
  push:
    branches:
    - v3-develop

jobs:
  publish:
    runs-on: ubuntu-latest # ¯\_(ツ)_/¯
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # TODO: add lint step before building.

    - name: Build
      uses: docker://thulioassis/bazel-docker-image:0.29.0
      with:
        args: bash .github/workflows/publish/build.sh

    - name: Rename
      run: bash .github/workflows/publish/rename.sh

    - name: Verify
      run: bash .github/workflows/publish/verify.sh

    - name: Publish
      uses: docker://minio/mc
      with:
        entrypoint: .github/workflows/publish/publish.sh
      env:
        BUCKET: scf-v3
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
